CONFIG = {
    "cs_to_mapi": {
        0: 10,
        1: 0,
        2: 1,  # sidewalk "Curb",
        3: 4,  # "Fence",
        4: 4,  # fence, "Guard Rail",
        5: 4,  # fence "Barrier",
        6: 3,  # wall, "Wall",
        7: 0,  # road "Bike Lane",
        8: 0,  # road "Crosswalk - Plain",
        9: 1,  # sidewalk "Curb Cut",
        10: 0,  # road "Parking",
        11: 1,  # sidewalk "Pedestrian Area",
        # 12: 0,  # road"Rail Track",
        12: 16,  # train "Rail Track",
        13: 0,  # road 0,  # road"Road",
        14: 0,  # road "Service Lane",
        15: 1,  # sidewalk"Sidewalk",
        16: 0,  # road "Bridge",
        17: 2,  # building "Building",
        # 18: 2,  # building "Tunnel",
        18: 3,  # wall "Tunnel",
        19: 11,  # person "Person",
        20: 12,  # rider "Bicyclist",
        21: 12,  # rider "Motorcyclist",
        22: 12,  # rider "Other Rider",
        23: 0,  # road "Lane Marking - Crosswalk",
        24: 0,  # road "Lane Marking - General",
        25: 9,  # terrain "Mountain",
        26: 9,  # terrain "Sand",
        27: 10,  # sky "Sky",
        28: 9,  # terrain "Snow",
        29: 9,  # terrain "Terrain",
        30: 8,  # vegetation "Vegetation",
        31: 0,  # road "Water",
        # 32: 5,  # pole "Banner",
        32: 4,  # fence "Banner",
        33: 255,  # unlabeled "Bench",
        34: 255,  # unlabeled "Bike Rack",
        # 35: 255,  # unlabeled  "Billboard",
        35: 3,  # wall  "Billboard",
        36: 0,  # road "Catch Basin",
        37: 255,  # unlabeled "CCTV Camera",
        38: 255,  # unlabeled "Fire Hydrant",
        39: 255,  # unlabeled "Junction Box",
        40: 255,  # unlabeled "Mailbox",
        41: 0,  # road "Manhole",
        42: 2,  # building "Phone Booth",
        43: 0,  # road "Pothole",
        44: 6,  # unlabeled "Street Light",
        45: 5,  # pole "Pole",
        46: 7,  # traffic sign"Traffic Sign Frame",
        47: 5,  # pole "Utility Pole",
        48: 6,  # traffic light "Traffic Light",
        49: 7,  # traffic sign "Traffic Sign (Back)",
        50: 7,  # traffic sign "Traffic Sign (Front)",
        51: 255,  # unlabeled  "Trash Can",
        52: 18,  # bicycle "Bicycle",
        53: 13,  # unlabeled "Boat",
        54: 15,  # bus "Bus",
        55: 13,  # car "Car",
        56: 13,  # car "Caravan",
        57: 17,  # "Motorcycle",
        58: 16,  #train "On Rails",
        59: 13,  # unlabeled  "Other Vehicle",
        60: 14,  # car "Trailer",
        61: 14,  # truck "Truck",
        62: 255,  # unlabeled  "Wheeled Slow",
        63: 255,  # unlabeled "Car Mount",
        64: 13,  # unlabeled  "Ego Vehicle",
        65: 255,  # unlabeled "Unlabeled",

    }
}
