CONFIG = {
    "label2id": {
        'road': '0',
        # 'parking': '1',
        'drivable fallback': '1',
        'sidewalk': '2',
        # 'rail track': '3',
        'non-drivable fallback': '3',
        'person': '4',
        # 'animal': '4',
        'rider': '5',
        'motorcycle': '6',
        'bicycle': '7',
        'autorickshaw': '8',
        'car': '9',
        'truck': '10',
        'bus': '11',
        # 'caravan': '12',
        # 'trailer': '12',
        # 'train': '12',
        'vehicle fallback': '12',
        'curb': '13',
        'wall': '14',
        'fence': '15',
        'guard rail': '16',
        'billboard': '17',
        'traffic sign': '18',
        'traffic light': '19',
        'pole': '20',
        # 'polegroup': '20',
        'obs-str-bar-fallback': '21',
        'building': '22',
        'bridge': '23',
        # 'tunnel': '23',
        'vegetation': '24',
        'sky': '25',
        # 'fallback background': '25',
        # 'unlabeled': '255',
        # 'ego vehicle': '255',
        # 'rectification border': '255',
        # 'out of roi': '255',
        # 'license plate': '255',
        'unlabeled': '255'
  }
}